### ISSUE TITLE
Various bugs on Portugal's mission tree

### ISSUE THREAD

**Issue by Plutarc0** [Amazonys/Imperialism-Reinvigorated#89]
- [x] Mission “Fill the Treasury” reward provides -0.05 yearly inflation reduction, which is actually a malus. Should provide +0.05 yearly inflation reduction.

- [ ] Mission “Develop Lisbão” does not charge the player 500 ducats. - Also, should be Lisboa.

- [x] Mission “Develop Algarve” does not charge the player 250 ducats.

- [x] Mission “Develop Porto” does not charge the player 350 ducats.

- [x] Mission “Develop Beja” does not charge the player 350 ducats.

- [x] Mission “Casa da Guiné” displays as requiring only the highlighted province of Gabu (#1114), but cannot be taken when that requirement is met. Mission is also missing localization.

- [x] Mission “Seize Sofala” claims to grant a permanent claim on Zanzibar (#1201), but does not.

- [x] Mission “Route to Índia” can be taken long in advance of reaching India (known issue).

- [ ] Mission “Take Goa” does not give Portugal the province of Goa (#2030), but still rewards the local power with the province bonus. Mission does not give a permanent claim on Trincomalee (#4409).

- [x] Mission “Discover the Orient” can be taken long in advance of reaching China (known issue).

- [x] Mission “Colonize Chittagong” grants the province of Chittagong (#568) but requires you to discover Bijapur (#569).

**Comment by Jupiter0-0** [comment]
Should be fixed with the introduction of the excel-based mission trees.
